import { type CheckItem } from "./types";
import { findVersion } from "./utils";

export const EXPO_PACKAGES_CHECKS: Array<CheckItem | string> = [
  "expo modules",
  {
    id: "EXPO-HAPTICS",
    url: "/expo-haptics",
    title: "Haptics",
    description: "Haptic feedback",
    checkedIos: "checked",
    checkedAndroid: "unchecked",
    nativeModuleName: "expo-haptics",
    nativeModuleVersion: findVersion("expo-haptics"),
  },
  {
    id: "EXPO-LOCAL_AUTHENTICATION",
    url: "/expo-local-authentication",
    title: "Local Authentication",
    description: "Biometrics",
    checkedIos: "checked",
    checkedAndroid: "checked",
    nativeModuleName: "expo-local-authentication",
    nativeModuleVersion: findVersion("expo-local-authentication"),
  },
  {
    id: "EXPO-WEB-BROWSER",
    url: "/expo-web-browser",
    title: "Web Browser",
    description: "Web Browser",
    checkedIos: "checked",
    checkedAndroid: "checked",
    nativeModuleName: "expo-web-browser",
    nativeModuleVersion: findVersion("expo-web-browser"),
  },
  {
    id: "EXPO-AV",
    url: "/expo-av",
    title: "Expo AV",
    description: "Audio and Video",
    checkedIos: "checked",
    checkedAndroid: "checked",
    nativeModuleName: "expo-av",
    nativeModuleVersion: findVersion("expo-av"),
  },
  {
    id: "EXPO-TRACKING-TRANSPARENCY",
    url: "/expo-tracking-transparency",
    title: "Tracking Transparency",
    description: "Tracking Transparency (ios only)",
    checkedIos: "checked",
    checkedAndroid: "not-applicable",
    nativeModuleName: "expo-tracking-transparency",
    nativeModuleVersion: findVersion("expo-tracking-transparency"),
  },
  {
    id: "EXPO-STORE-REVIEW",
    url: "/expo-store-review",
    title: "Store Review",
    description: "Store Review",
    checkedIos: "checked",
    checkedAndroid: "unchecked",
    nativeModuleName: "expo-store-review",
    nativeModuleVersion: findVersion("expo-store-review"),
  },
  {
    id: "EXPO-CONSTANTS",
    url: "/expo-constants",
    title: "Constants",
    description: "Constants",
    checkedIos: "checked",
    checkedAndroid: "checked",
    nativeModuleName: "expo-constants",
    nativeModuleVersion: findVersion("expo-constants"),
  },
  {
    id: "EXPO-DEVICE",
    url: "/expo-device",
    title: "Device",
    description: "Device",
    checkedIos: "checked",
    checkedAndroid: "checked",
    nativeModuleName: "expo-device",
    nativeModuleVersion: findVersion("expo-device"),
  },
  {
    id: "EXPO-APPLICATION",
    url: "/expo-application",
    title: "Application",
    description: "Application",
    checkedIos: "checked",
    checkedAndroid: "checked",
    nativeModuleName: "expo-application",
    nativeModuleVersion: findVersion("expo-application"),
  },
  {
    id: "EXPO-RANDOM",
    url: "/expo-random",
    title: "Random",
    description: "Random",
    checkedIos: "checked",
    checkedAndroid: "checked",
    nativeModuleName: "expo-random",
    nativeModuleVersion: findVersion("expo-random"),
  },
  {
    id: "EXPO-BLUR",
    url: "/expo-blur",
    title: "Blur",
    description: "Blur view (works on ios only)",
    checkedIos: "checked",
    checkedAndroid: "not-applicable",
    nativeModuleName: "expo-blur",
    nativeModuleVersion: findVersion("expo-blur"),
  },
  {
    id: "EXPO-CLIPBOARD",
    url: "/expo-clipboard",
    title: "Clipboard",
    description: "Clipboard",
    checkedIos: "checked",
    checkedAndroid: "checked",
    nativeModuleName: "expo-clipboard",
    nativeModuleVersion: findVersion("expo-clipboard"),
  },
  {
    id: "EXPO-BARCODE-SCANNER",
    url: "/expo-barcode-scanner",
    title: "Barcode Scanner",
    description: "Barcode Scanner",
    checkedIos: "checked",
    checkedAndroid: "unchecked",
    nativeModuleName: "expo-barcode-scanner",
    nativeModuleVersion: findVersion("expo-barcode-scanner"),
  },
  {
    id: "EXPO-SECURE-STORE",
    url: "/expo-secure-store",
    title: "Secure Store",
    description: "Secure Store",
    checkedIos: "checked",
    checkedAndroid: "checked",
    nativeModuleName: "expo-secure-store",
    nativeModuleVersion: findVersion("expo-secure-store"),
  },
  {
    id: "EXPO-LOCALIZATION",
    url: "/expo-localization",
    title: "Localization",
    description: "Localization",
    checkedIos: "checked",
    checkedAndroid: "checked",
    nativeModuleName: "expo-localization",
    nativeModuleVersion: findVersion("expo-localization"),
  },
  {
    id: "EXPO-NOTIFICATIONS",
    url: "/expo-notifications",
    title: "Notifications",
    description: "Notifications",
    checkedIos: "checked",
    checkedAndroid: "checked",
    nativeModuleName: "expo-notifications",
    nativeModuleVersion: findVersion("expo-notifications"),
  },
];
